- name: Ensure nftables is installed
  apt:
    name: nftables
    state: latest
    update_cache: yes

- name: Ensure NAT is enabled in nftables configuration
  blockinfile:
    path: /etc/nftables.conf
    block: |
      table nat {
          chain prerouting {
              type nat hook prerouting priority -100; policy accept;
          }
          chain postrouting {
              type nat hook postrouting priority 100; policy accept;
              oifname eth0 masquerade
          }
      }
  register: nftables_conf

- name: Restart the nftables service
  service:
    name: nftables
    state: restarted
  when: nftables_conf.changed

- name: Ensure the nftables service is set to start at boot
  service:
    name: nftables
    state: started
    enabled: yes