- name: Ensure necessary features are installed
  ansible.windows.win_feature:
    name:
      - Routing
      - RSAT-RemoteAccess-PowerShell
    state: present
  register: win_features

- name: Ensure the Remote Access service is started and starts at boot
  ansible.windows.win_service:
    name: RemoteAccess 
    start_mode: auto
    state: started

- name: Reboot if required by feature install
  win_reboot:
  when: win_features.reboot_required

- name: Ensure NAT is enabled from the internal network
  ansible.windows.win_powershell:
    script: |
      if ((Get-NetNat).InternalIPInterfaceAddressPrefix -ne "172.16.1.0/24") {
        New-NetNat -Name NAT -InternalIPInterfaceAddressPrefix "172.16.1.0/24"
      } else {
        $Ansible.Changed = $False
      }