- hosts: router
  become: true
  roles:
    - ipv4_forwarding

- hosts: router-l1
  become: true
  roles:
    - nftables_nat

- hosts: router-l2
  become: true
  roles:
    - nftables_nat

- hosts: router-l3
  become: true
  roles:
    - nftables_nat

- hosts: linux
  become: true
  roles:
    - apt_basic_packages

- hosts: windows
  roles:
    - win_firewall_ping