- hosts: router
  become: true
  roles:
    - ipv4_forwarding

- hosts: router_l1
  become: true
  roles:
    - nftables_nat

- hosts: router_l2
  become: true
  roles:
    - nftables_nat

- hosts: router_l3
  become: true
  roles:
    - nftables_nat

- hosts: linux
  become: true
  roles:
    - apt_basic_packages

- hosts: windows
  roles:
    - win_firewall_ping
    - win_internet_dns

- hosts: win_router
  roles:
    - win_routing_feature